### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by bencevans** [bencevans/node-oyster#6]
I think TFL may have changed something again as it's broken my login. Hopefully investigate soon. Having some sort of debug option so a log can be sent to inspect would be useful.

**Comment by charliedowler** [comment]
Ah, lucky I held off publishing oyster-history for a few days.

Would this be appropriate `function Oyster(username, password, [options], callback)`?

Might be overkill but this might be cool to log requests, regex results and exceptions => https://www.npmjs.com/package/dev-logger

**Comment by charliedowler** [comment]
I just tested this with my account. Working for me...

**Comment by bencevans** [comment]
Haha, works fine for me now too! Must've been the TFL site mucking up, I
imagine it's had quite a bit of use today given all these busses striking!

**Comment by bencevans** [comment]
Started using `debug` to check where things were going funny in oyster-cli (https://github.com/bencevans/oyster-cli/tree/debug), probably just use debug in this module too :)
