### ISSUE TITLE
Module is broken

### ISSUE THREAD

**Issue by tschoffelen** [bencevans/node-oyster#9]
Today, TfL seems to have released a new version of their website that breaks this library. I tried to implement a fix myself, but couldn't figure out where the source of the problem is. Would love to hear it if someone else is able to figure it out.

Cheers!

**Comment by bencevans** [comment]
TFL have moved to their contactless site for both Oyster and contactless cards now. Unfortunately they don't provide an API with the new site so this module needs rewriting to scrape https://contactless.tfl.gov.uk/DashBoard
